version: v1
description: Workflow to echo a nice hello world message to the logs
variables: null
steps:
  - name: Step 1
    description: ""
    image: alpine:latest
    input:
      - echo "Hello world. I am Step 1"
      - sleep 2
  - name: Step 2
    description: ""
    image: alpine:latest
    input:
      - echo "Hello world. I am Step 2"
    dependsOn:
      - Step 1
  - name: Step 3
    description: ""
    image: alpine:latest
    input:
      - echo "Hello world. I am Step 3"
    dependsOn:
      - Step 1
  - name: Step 4
    description: ""
    image: alpine:latest
    input:
      - echo "Hello world. I am Step 4"
    dependsOn:
      - Step 2
  - name: Step 5
    description: ""
    image: alpine:latest
    input:
      - echo "Hello world. I am Step 5"
    dependsOn:
      - Step 2
  - name: Step 6
    description: ""
    image: alpine:latest
    input:
      - echo "Hello world. I am Step 6"
    dependsOn:
      - Step 3
  - name: Step 7
    description: ""
    image: alpine:latest
    input:
      - echo "Hello world. I am Step 7"
    dependsOn:
      - Step 3

